name: ci
on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0.x' 

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        env:
          DOTNET_ENVIRONMENT: Testing
          DATAPROTECTION__APPNAME: TaskManager.CI.${{ github.run_id }}
        run: dotnet test --no-build -c Release --logger "trx;LogFileName=test-results.trx"
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'